### ISSUE TITLE
cannot open quick panel while having "Find Results" tab opened

### ISSUE THREAD

**Issue by revlis7** [rajeshvaya/Sublime-Extended-Tab-Switcher#6]
After doing a search in the project files. I can't open the quick panel by shortcut keys until I close the "Find Results" tab. Here is the error message:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 524, in run_
    return self.run(**args)
  File "ExtendedSwitcher in /Users/kevin/Library/Application Support/Sublime Text 3/Installed Packages/ExtendedTabSwitcher.sublime-package", line 55, in run
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 352, in show_quick_panel
    flat_items.append(items[i][j])
IndexError: list index out of range
```

**Comment by dmyger** [comment]
Set "show_full_file_path": false also helps.
But, will no shown file's paths ((

**Comment by rajeshvaya** [comment]
Thanks to @qsvui this should be fixed. I have tagged another release (2.3.1) and should be updated soon in the package control as well
